version: '3'
services:
  jenkins:
    image:: devopsifyio/jenkins-build-dep:alpine
    environment:
    - AWS_DEFAULT_REGION=us-east-1
    ports:
    - 80:8080
    - 50000:50000
    volumes:
    - /home/jenkins/workspace:/home/jenkins/workspace
    - /var/run/docker.sock:/var/run/docker.sock
    - /efs/jenkins_home:/var/jenkins_home
    privileged: true
    restart: on-failure
